eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eureka.server.eviction-interval-timer-in-ms: 5000
---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/


server:
  port: 9000
spring:
  profiles: dev9000



---

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/,http://localhost:9002/eureka/

server:
  port: 9001
spring:
  profiles: dev9001




---

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/,http://localhost:9001/eureka/


server:
  port: 9002
spring:
  profiles: dev9002